plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.4.0'
}

group 'com.chenying'
version '1.1'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.9.0'
    implementation 'net.java.dev.jna:jna-platform:5.9.0'
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2021.1'
    plugins = ['java', 'yaml']
}

patchPluginXml {
    sinceBuild '173.0'
    untilBuild null
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
} 